#!/usr/bin/env zsh

# pre-compiles zsh functions

mkzwc() {
    autoload -U zrecompile

    # compile functions found in $fpath
    for p ($fpath); do
        for a (`find $p -type f -not -name '*.zwc' -not -name '*.old'`); do
            zrecompile -p $a
        done
    done

    # compile zsh files
    conf=(~/.zshrc ~/.zsh/zeesh.zsh ~/.zcompdump)
    for a ($conf); do
        zrecompile -p $a
    done

    # compile plugins
    for a ($zeesh_plugins); do
        zrecompile -p ~/.zsh/plugins/$a/plugin
    done
    unset a p conf
}
