#!/bin/sh

if [[ $# == 0 ]]; then
    git commit
else
    message=''
    for i in "$@"; do
        if [ "$message" ]; then
            message="$message $i"
        else
            message="$i"
        fi
    done
    git commit -m "$message"
fi
