#!/bin/sh

if [ ! `hash hub 2>/dev/null` ]; then
    echo git-pull-request-auto requires hub.
    exit 1
fi

if [ $1 ]; then
    # Make sure we've pulled from origin first
    git fetch origin

    repo=`git config remote.origin.url | cut -d '/' -f4-`
    url="https://github.com/$repo/pull/$1"
    hub merge $url
else
    echo Specify pull request number
fi
