#!/bin/bash

set -e

(
    branch() {
        git branch 2>/dev/null | grep -e '^*' | tr -d '\* '
    }

    ensure_valid_ref() {
        ref=$1
        (
            set +e
            git show-ref $ref > /dev/null
            if [[ $? == 1 ]]; then
                echo "$0: bad ref: $ref"
                exit 1
            fi
        )
    }

    show_rev() {
        rev=$1
        git --no-pager log -1 $rev --graph --pretty=format:'%C(yellow)%h%Cblue%d%Creset %s %C(white)%an, %ar%Creset'
        echo
        git --no-pager diff --stat $rev^..$rev
        echo
    }

    if [[ $# == 2 ]]; then
        LOCAL=$1
        REMOTE=$2
    elif [[ $# == 1 ]]; then
        LOCAL=`branch`
        REMOTE=$1
    else
        LOCAL=`branch`
        REMOTE=origin/$LOCAL
    fi

    ensure_valid_ref $LOCAL
    ensure_valid_ref $REMOTE

    echo "changes from local ${LOCAL} to remote ${REMOTE}:"

    echo
    echo incoming:
    for rev in `git rev-list $LOCAL..$REMOTE`; do
        show_rev $rev
    done

    echo
    echo outgoing:
    for rev in `git rev-list $REMOTE..$LOCAL`; do
        show_rev $rev
    done
)
