#!/usr/bin/env zsh

if [ `hash hub 2>/dev/null` ]; then
    echo git-pull-request-auto requires hub.
    exit 1
fi

branch=`git rev-parse --abbrev-ref HEAD`
origin_user=`git config remote.origin.url | cut -d '/' -f 4`
upstream_user=`git config remote.upstream.url | cut -d '/' -f 4`

# owner of repo to open pull request to
if [ ! "$upstream_user" ]; then
    echo 'You need to add an upstream remote'
    echo 'git remote add upstream <url>'
    exit 1
fi

# branch to open pull request against
base_branch=`git config pull-request-auto.$branch` # try branch-specific setting
if [ ! "$base_branch" ]; then
    base_branch=`git config pull-request-auto.base` # try global settings
fi

if [ ! "$base_branch" ]; then
    base_branch=master # fallback to master if unspecified
fi

# make this branch track origin branch of same name and push it
git push --set-upstream origin $branch

# do pull request
hub pull-request -b $upstream_user:$base_branch -h $origin_user:$branch
