#!/bin/sh

if [ $# -lt 2 ]; then
    # expects origin/foo format
    arg=( `echo ${$1//\// }` )
    remote=$arg[1]
    branch=$arg[2]
else
    # expects origin foo format
    remote=$1
    branch=$2
fi

git pull
git checkout -b $branch $remote/$branch
