#!/bin/sh

if [[ $# == 0 ]]; then
    git commit -a
else
    for i in "$@"; do
        if [ "$message" ]; then
            message="$message $i"
        else
            message="$i"
        fi
    done
    git commit -a -m "$message"
fi
