#!/usr/bin/env zsh

# parse arguments
args=()
words=()
i=1
while [ $i -le $# ]; do
    arg="${@[$i]}"
    case $arg in
    -*)
        args[$i]=$arg
    ;;
    *)
        words[$i]=$arg
    ;;
    esac
    let i++
done

# join message
message=''
for i in ${words[*]}; do
    if [ "$message" ]; then
        message="$message $i"
    else
        message="$i"
    fi
done

if [ "$message" ]; then
    git commit ${args[*]} -m "$message"
else
    git commit ${args[*]}
fi
